### ISSUE TITLE
可不可以让textinput 获取焦点，同时不显示软键盘？

### ISSUE THREAD

**Issue by jingxin2015** [DanielMSchmidt/react-native-dismiss-keyboard#10]
可不可以让textinput 获取焦点，同时不显示软键盘？

**Comment by DanielMSchmidt** [comment]
Hi there, unfortunately, I don't speak your language, could you translate your issue in English for me?

**Comment by jingxin2015** [comment]
Can you get the textinput component to focus and not display the soft keyboard?

**Comment by DanielMSchmidt** [comment]
Unfortunately this is as far as I know impossible. If you find a solution, please let me know and I will add it to the README. Thanks for your help!
