### ISSUE TITLE
Not working for RN 0.25.1

### ISSUE THREAD

**Issue by CoericK** [DanielMSchmidt/react-native-dismiss-keyboard#3]

**Comment by DanielMSchmidt** [comment]
Thanks for filing this issue. I will try to fix this issue ASAP 👍

**Comment by CoericK** [comment]
@DanielMSchmidt No Problem, please let me know when this is fixed.

**Comment by DanielMSchmidt** [comment]
@CoericK Hi, I just updated the Demo (misread you issue, thought you meant 0.26.1). The last version of the demo was for 0.25.1, as you may see [here](https://github.com/DanielMSchmidt/DismissKeyboardExample/tree/a0929f7dc200c4c68b3b5e1f03862c587f78bc81) and worked completely fine on my system. Would you mind checking this project and commit out and test if this works for you, too?

**Comment by DanielMSchmidt** [comment]
I assume it worked for you, otherwise, please write again.
