### ISSUE TITLE
Add `react-native` to `peerDependencies` for monorepo support

### ISSUE THREAD

**Issue by kevinwolfcr** [DanielMSchmidt/react-native-dismiss-keyboard#30]
Hello. I was trying to run this from a monorepo setup but ran into the issue `Unable to resolve module from /MyLocation/workspace-root/node_modules/react-native-dismiss-keyboard`.

This is happening because `react-native` is not listed on the `peerDependencies`, so Lerna is hoisting this package on the monorepo root.

I did fixed this by adding `**/react-native-dismiss-keyboard` and  `**/react-native-dismiss-keyboard/**` to the `nohoist` configuration of the package.json. But I think that should be a temporary fix.

**Comment by DanielMSchmidt** [comment]
This makes sense, as you already did the research, would you like to also do the PR?
