### ISSUE TITLE
Looks like this is already in RN

### ISSUE THREAD

**Issue by wootwoot1234** [DanielMSchmidt/react-native-dismiss-keyboard#4]
Thought it would be good to tell people that this code ships with RN.  You can include it here:
```
import dismissKeyboard from 'dismissKeyboard';
```

Here's a link to the code in RN: https://github.com/facebook/react-native/blob/master/Libraries/Utilities/dismissKeyboard.js

Might save people the trouble of adding an extra module if something was added about it already being available in RN to the top of the readme file.

**Comment by DanielMSchmidt** [comment]
Hey, 
nice idea. The reason I wrote this small module was that importing the dismissKeyboard module from react native often broke in my setups, especially after updating RN. Would it be okay for you if I wrote something like that in the readme?

**Comment by wootwoot1234** [comment]
I think that's a great idea. It does seem like it's not totally supported
and is definitely not documented. That's good to know that it has not
worked in other versions of RN.
