### ISSUE TITLE
Add Version Table Support

### ISSUE THREAD

**Issue by dangnelson** [DanielMSchmidt/react-native-dismiss-keyboard#6]
I'm working on a standard for displaying version support on React-Native module README files. I would love your feedback: [react-native-version-support-table](https://github.com/dangnelson/react-native-version-support-table)

**Comment by DanielMSchmidt** [comment]
Hey, thanks for your input. I have something similar for React Native only installed because I don't have any iOS or Android specific code included. I think it is a good way to go for more complex projects, thanks for your work!

**Comment by dangnelson** [comment]
Oh what are you using? Didn't realize anything already existed?

**Comment by DanielMSchmidt** [comment]
I simply defined my own grid [here](https://github.com/DanielMSchmidt/react-native-dismiss-keyboard#support)
