### ISSUE TITLE
Doesn't work with React-Native 0.30.0 inside webview

### ISSUE THREAD

**Issue by RyanMitchellWilson** [DanielMSchmidt/react-native-dismiss-keyboard#8]
Trying to use this with a native button in my app to dismiss the keyboard while inside a webview. My onPress function looks like so:
```
const closeKeyboard() {
  console.log('Close the Keyboard');
  dismissKeyboard();
}
```
I see the console log but the keyboard just sits there.

**Comment by DanielMSchmidt** [comment]
I am sorry, but this module is just for the usage in React Native. 
I am not sure if I would like to change the scope of this project or not.

**Comment by RyanMitchellWilson** [comment]
A WebView is part of React-Native https://facebook.github.io/react-native/docs/webview.html. A webView is just a different view inside your app that just shows a webpage.

**Comment by DanielMSchmidt** [comment]
Yes, indeed, but the keyboard displayed is issued by the web page in the web view. This means it is not controlled by React Native, but by the Browser used in a Web View. I will add a section to the Readme with further information on how to tackle this problem, e.g. with [this trick](http://stackoverflow.com/questions/8335834/how-can-i-hide-the-android-keyboard-using-javascript).

I feel like adding such a hack to this project will dramatically increase its size in contrast to the benefit for most users. But I guess giving a solution for our users would be nice as it is a kind of related topic.
