### ISSUE TITLE
How not to show keyboard at all? 

### ISSUE THREAD

**Issue by N-W-Turash** [DanielMSchmidt/react-native-dismiss-keyboard#9]
Even if after calling the dissmisskeyboard() function, the keyboard appears for a while and then hide. How to make it completely not appearing at all?

**Comment by DanielMSchmidt** [comment]
Hey, 

Thanks for reaching out. Could you explain your scenario a bit more? Maybe with a small [RNPlay](https://rnplay.org/) example, so I can see what you mean. That would be super helpful!

**Comment by DanielMSchmidt** [comment]
Close due to inactivity
